# Google
spring.security.oauth2.client.registration.google.client-id=63560044495-ea70lr1a16iv7d8a9d5vfqaeha0an11b.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
# GitHub
spring.security.oauth2.client.registration.github.client-id=Ov23liRHOj3P6L8F3bjQ
spring.security.oauth2.client.registration.github.client-secret=bf8827f092484f9765b56841d011145be9df733e